package ins.platform.menu.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SmcMenu generated by Tools.Don't edit.
 */
@Entity
@Table(name = "smc_menu")
public class SmcMenu implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 序号 */
	private Integer id;
	/** 上级菜单ID */
	private Integer upperId;
	/** 菜单级别 */
	private Integer menuLevel;
	/** 系统代码 */
	private String systemCode;
	/** 菜单中文名称 */
	private String menuCName;
	/** 菜单英文名称 */
	private String menuEName;
	/** 执行URL */
	private String actionURL;
	/** 目标 */
	private String target;
	/** 显示序号 */
	private float displayNo;
	/** 任务代码 */
	private String taskCode;
	/** 有效标志 */
	private String validInd;
	/** 图片路径 */
	private String image;
	/** 属性允许险类 */
    private String permitRiskClass;
    /** 属性允许险类除外险种 */
    private String exceptRiskCode;
    /** 属性禁止险类 */
    private String exceptRiskClass;
    /** 属性禁止险类除外险种 */
    private String permitRiskCode;

	public SmcMenu() {
	}

	/**
	 * 序号
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * 上级菜单ID
	 */
	@Column(name = "UpperId")
	public Integer getUpperId() {
		return this.upperId;
	}

	public void setUpperId(Integer upperId) {
		this.upperId = upperId;
	}

	/**
	 * 菜单级别
	 */
	@Column(name = "MenuLevel")
	public Integer getMenuLevel() {
		return menuLevel;
	}

	public void setMenuLevel(Integer menuLevel) {
		this.menuLevel = menuLevel;
	}

	/**
	 * 系统代码
	 */

	@Column(name = "SystemCode")
	public String getSystemCode() {
		return this.systemCode;
	}

	public void setSystemCode(String systemCode) {
		this.systemCode = systemCode;
	}

	/**
	 * 菜单中文名称
	 */

	@Column(name = "MenuCName")
	public String getMenuCName() {
		return this.menuCName;
	}

	public void setMenuCName(String menuCName) {
		this.menuCName = menuCName;
	}

	/**
	 * 菜单英文名称
	 */

	@Column(name = "MenuEName")
	public String getMenuEName() {
		return this.menuEName;
	}

	public void setMenuEName(String menuEName) {
		this.menuEName = menuEName;
	}

	/**
	 * 执行URL
	 */

	@Column(name = "ActionURL")
	public String getActionURL() {
		return this.actionURL;
	}

	public void setActionURL(String actionURL) {
		this.actionURL = actionURL;
	}

	/**
	 * 目标
	 */

	@Column(name = "Target")
	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	/**
	 * 显示序号
	 */

	@Column(name = "DisplayNo")
	public float getDisplayNo() {
		return this.displayNo;
	}

	public void setDisplayNo(float displayNo) {
		this.displayNo = displayNo;
	}

	/**
	 * 任务代码
	 */

	@Column(name = "TaskCode")
	public String getTaskCode() {
		return this.taskCode;
	}

	public void setTaskCode(String taskCode) {
		this.taskCode = taskCode;
	}

	/**
	 * 有效标志
	 */

	@Column(name = "ValidInd")
	public String getValidInd() {
		return this.validInd;
	}

	public void setValidInd(String validInd) {
		this.validInd = validInd;
	}

	/**
	 * 图片路径
	 */

	@Column(name = "Image")
	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}
	
	@Column(name = "PermitRiskClass")
	public String getPermitRiskClass() {
		return permitRiskClass;
	}

	public void setPermitRiskClass(String permitRiskClass) {
		this.permitRiskClass = permitRiskClass;
	}

	@Column(name = "ExceptRiskCode")
	public String getExceptRiskCode() {
		return exceptRiskCode;
	}

	public void setExceptRiskCode(String exceptRiskCode) {
		this.exceptRiskCode = exceptRiskCode;
	}

	@Column(name = "ExceptRiskClass")
	public String getExceptRiskClass() {
		return exceptRiskClass;
	}

	public void setExceptRiskClass(String exceptRiskClass) {
		this.exceptRiskClass = exceptRiskClass;
	}

	@Column(name = "PermitRiskCode")
	public String getPermitRiskCode() {
		return permitRiskCode;
	}

	public void setPermitRiskCode(String permitRiskCode) {
		this.permitRiskCode = permitRiskCode;
	}
}
