package cn.com.sinosoft.saa.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * SaaCompany generated by Tools.Don't edit.
 */
@Entity
@Table(name = "saa_company")
public class SaaCompany implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** ����� */
	private String comCode;
	private String comCname;
	private String uppercomcode;
	private String AgentInsFlag;
	private String AgentInsCom;
	private String belongComCode;
	private String comLevel;
	/** Чf״̬ */
	private String validStatus;
	private String hrCompanyID;

	public SaaCompany() {
	}

	/**       
	 * �����
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "comcode")
	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	@Column(name = "ComCName")
	public String getComCname() {
		return this.comCname;
	}

	public void setComCname(String comCname) {
		this.comCname = comCname;
	}

	@Column(name = "uppercomcode")
	public String getUppercomcode() {
		return this.uppercomcode;
	}

	public void setUppercomcode(String uppercomcode) {
		this.uppercomcode = uppercomcode;
	}

		@Column(name = "agentinsflag")
	public String getAgentInsFlag() {
		return AgentInsFlag;
	}

	public void setAgentInsFlag(String agentInsFlag) {
		AgentInsFlag = agentInsFlag;
	}

	@Column(name = "agentinscom")
	public String getAgentInsCom() {
		return AgentInsCom;
	}

	public void setAgentInsCom(String agentInsCom) {
		AgentInsCom = agentInsCom;
	}

	@Column(name = "BelongComCode")
	public String getBelongComCode() {
		return this.belongComCode;
	}

	public void setBelongComCode(String belongComCode) {
		this.belongComCode = belongComCode;
	}

	@Column(name = "ComLevel")
	public String getComLevel() {
		return this.comLevel;
	}

	public void setComLevel(String comLevel) {
		this.comLevel = comLevel;
	}

	/**       
	 * Чf״̬
	 */

	@Column(name = "validstatus")
	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}
	
	@Column(name = "hrCompanyID")
	public String getHrCompanyID() {
		return hrCompanyID;
	}

	public void setHrCompanyID(String hrCompanyID) {
		this.hrCompanyID = hrCompanyID;
	}

}
