package cn.com.sinosoft.saa.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * SaaUser generated by Tools.Don't edit.
 */
@Entity
@Table(name = "hyuser")
public class SaaUser implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 用户名代码 */
	private String userCode;
	/** 用户名 */
	private String userName;
	/** 密码 */
	
	private String password;
	/** 电话号码 */
	private String phone;

	public SaaUser() {
	}

	/**       
	 * 用户名代码
	 */
	@Id
	@Column(name = "usercode")
	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	/**       
	 * 用户名名称
	 */

	@Column(name = "username")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**       
	 * 密码
	 */

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	@Column(name = "phone")
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	

}
