package cn.com.expense.eps.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EpsCompany generated by Tools.Don't edit.
 */
@Entity
@Table(name = "EPSCOMPANY")
public class EpsCompany implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 成本中心 */
	private String comCode;
	/** 机构名称 */
	private String comCName;
	/** 机构英文名称 */
	private String comEName;
	/** 上级机构代码 */
	private String upperComCode;
	/** 机构级别 */
	private String comLevel;
	/** 标志 */
	private String centerFlag;
	/** 有效状�??(0 无效,1 有效) */
	private String validStatus;
	/** AgentInsCom */
	private String agentInsCom;
	/** BelongComCode */
	private String belongComCode;
	/** HrCompanyID */
	private String hrCompanyID;
	/** AgentInsFlag */
	private String agentInsFlag;
	private List<EpsUser> epsUsers = new ArrayList<EpsUser>(0);

	public EpsCompany() {
	}

	/**       
	 * 成本中心
	 */
	@Id
	@Column(name = "COMCODE")
	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	/**       
	 * 机构名称
	 */

	@Column(name = "COMCNAME")
	public String getComCName() {
		return this.comCName;
	}

	public void setComCName(String comCName) {
		this.comCName = comCName;
	}

	/**       
	 * 机构英文名称
	 */

	@Column(name = "COMENAME")
	public String getComEName() {
		return this.comEName;
	}

	public void setComEName(String comEName) {
		this.comEName = comEName;
	}

	/**       
	 * 上级机构代码
	 */

	@Column(name = "UPPERCOMCODE")
	public String getUpperComCode() {
		return this.upperComCode;
	}

	public void setUpperComCode(String upperComCode) {
		this.upperComCode = upperComCode;
	}

	/**       
	 * 机构级别
	 */

	@Column(name = "COMLEVEL")
	public String getComLevel() {
		return this.comLevel;
	}

	public void setComLevel(String comLevel) {
		this.comLevel = comLevel;
	}

	/**       
	 * 标志
	 */

	@Column(name = "CENTERFLAG")
	public String getCenterFlag() {
		return this.centerFlag;
	}

	public void setCenterFlag(String centerFlag) {
		this.centerFlag = centerFlag;
	}

	/**       
	 * 有效状�??(0 无效,1 有效)
	 */

	@Column(name = "VALIDSTATUS")
	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	/**       
	 * AgentInsCom
	 */

	@Column(name = "AGENTINSCOM")
	public String getAgentInsCom() {
		return this.agentInsCom;
	}

	public void setAgentInsCom(String agentInsCom) {
		this.agentInsCom = agentInsCom;
	}

	/**       
	 * BelongComCode
	 */

	@Column(name = "BELONGCOMCODE")
	public String getBelongComCode() {
		return this.belongComCode;
	}

	public void setBelongComCode(String belongComCode) {
		this.belongComCode = belongComCode;
	}

	/**       
	 * HrCompanyID
	 */

	@Column(name = "HRCOMPANYID")
	public String getHrCompanyID() {
		return this.hrCompanyID;
	}

	public void setHrCompanyID(String hrCompanyID) {
		this.hrCompanyID = hrCompanyID;
	}

	/**       
	 * AgentInsFlag
	 */

	@Column(name = "AGENTINSFLAG")
	public String getAgentInsFlag() {
		return this.agentInsFlag;
	}

	public void setAgentInsFlag(String agentInsFlag) {
		this.agentInsFlag = agentInsFlag;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "epsCompany")
	public List<EpsUser> getEpsUsers() {
		return this.epsUsers;
	}

	public void setEpsUsers(List<EpsUser> epsUsers) {
		this.epsUsers = epsUsers;
	}

}
