package cn.com.expense.eps.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EpsPayWay generated by Tools.Don't edit.
 */
@Entity
@Table(name = "EPSPAYWAY")
public class EpsPayWay implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 收付方式代码 */
	private String payWayCode;
	/** 收付方式中文名称 */
	private String payWayCName;
	/** 收付方式英文名称 */
	private String payWayEName;
	/** 收付方式属�??(* 收付,1 �?,2 �?) */
	private String payWayType;
	/** �?/贷标�? */
	private String dcInd;
	/** 试用收付类型 */
	private String permitPayType;
	/** 业务支付方式 */
	private String opPayWay;
	/** 适用机构 */
	private String permitCenterCode;
	/** 除外机构 */
	private String exceptCenterCode;
	/** 科目代码相关�?(0 无其他相关�??,1 与银行帐户相�?) */
	private String titleRelation;
	/** 会计科目编码 */
	private String titleCode;
	/** 会计科目名称 */
	private String titleName;
	/** F01 险类档案 */
	private String f01;
	/** F02保监会分�? */
	private String f02;
	/** F03核算单位 */
	private String f03;
	/** F05险种档案 */
	private String f05;
	/** F04部门档案 */
	private String f04;
	/** F06业务性质 */
	private String f06;
	/** F07业务来源 */
	private String f07;
	/** F08车型档案 */
	private String f08;
	/** F09共保人档�? */
	private String f09;
	/** F10再保人档�? */
	private String f10;
	/** F11客商辅助核算 */
	private String f11;
	/** F13 险别档案 */
	private String f13;
	/** F12业务员档�? */
	private String f12;
	/** F14 投资品种 */
	private String f14;
	/** F15 农业补贴来源 */
	private String f15;
	/** F16 */
	private String f16;
	/** F17 */
	private String f17;
	/** F18 */
	private String f18;
	/** F19 */
	private String f19;
	/** F20 */
	private String f20;
	/** F21 */
	private String f21;
	/** F22 */
	private String f22;
	/** F23 */
	private String f23;
	/** F24 */
	private String f24;
	/** F25 */
	private String f25;
	/** F26 */
	private String f26;
	/** F27现金流量项目 */
	private String f27;
	/** F28 �?来单�? */
	private String f28;
	/** F29银行代码 */
	private String f29;
	/** F30帐户档案 */
	private String f30;
	/** 创建日期 */
	private Date createDat;
	/** 创建人代�? */
	private String createCode;
	/** 有效状�??(0 无效,1 有效) */
	private String validStatus;
	/** 修改日期 */
	private Date updateDate;
	/** 修改人代�? */
	private String updateCode;
	/** 备注 */
	private String remark;
	/** 预留标志 */
	private String flag;

	public EpsPayWay() {
	}

	/**       
	 * 收付方式代码
	 */
	@Id
	@Column(name = "PAYWAYCODE")
	public String getPayWayCode() {
		return this.payWayCode;
	}

	public void setPayWayCode(String payWayCode) {
		this.payWayCode = payWayCode;
	}

	/**       
	 * 收付方式中文名称
	 */

	@Column(name = "PAYWAYCNAME")
	public String getPayWayCName() {
		return this.payWayCName;
	}

	public void setPayWayCName(String payWayCName) {
		this.payWayCName = payWayCName;
	}

	/**       
	 * 收付方式英文名称
	 */

	@Column(name = "PAYWAYENAME")
	public String getPayWayEName() {
		return this.payWayEName;
	}

	public void setPayWayEName(String payWayEName) {
		this.payWayEName = payWayEName;
	}

	/**       
	 * 收付方式属�??(* 收付,1 �?,2 �?)
	 */

	@Column(name = "PAYWAYTYPE")
	public String getPayWayType() {
		return this.payWayType;
	}

	public void setPayWayType(String payWayType) {
		this.payWayType = payWayType;
	}

	/**       
	 * �?/贷标�?
	 */

	@Column(name = "DCIND")
	public String getDcInd() {
		return this.dcInd;
	}

	public void setDcInd(String dcInd) {
		this.dcInd = dcInd;
	}

	/**       
	 * 试用收付类型
	 */

	@Column(name = "PERMITPAYTYPE")
	public String getPermitPayType() {
		return this.permitPayType;
	}

	public void setPermitPayType(String permitPayType) {
		this.permitPayType = permitPayType;
	}

	/**       
	 * 业务支付方式
	 */

	@Column(name = "OPPAYWAY")
	public String getOpPayWay() {
		return this.opPayWay;
	}

	public void setOpPayWay(String opPayWay) {
		this.opPayWay = opPayWay;
	}

	/**       
	 * 适用机构
	 */

	@Column(name = "PERMITCENTERCODE")
	public String getPermitCenterCode() {
		return this.permitCenterCode;
	}

	public void setPermitCenterCode(String permitCenterCode) {
		this.permitCenterCode = permitCenterCode;
	}

	/**       
	 * 除外机构
	 */

	@Column(name = "EXCEPTCENTERCODE")
	public String getExceptCenterCode() {
		return this.exceptCenterCode;
	}

	public void setExceptCenterCode(String exceptCenterCode) {
		this.exceptCenterCode = exceptCenterCode;
	}

	/**       
	 * 科目代码相关�?(0 无其他相关�??,1 与银行帐户相�?)
	 */

	@Column(name = "TITLERELATION")
	public String getTitleRelation() {
		return this.titleRelation;
	}

	public void setTitleRelation(String titleRelation) {
		this.titleRelation = titleRelation;
	}

	/**       
	 * 会计科目编码
	 */

	@Column(name = "TITLECODE")
	public String getTitleCode() {
		return this.titleCode;
	}

	public void setTitleCode(String titleCode) {
		this.titleCode = titleCode;
	}

	/**       
	 * 会计科目名称
	 */

	@Column(name = "TITLENAME")
	public String getTitleName() {
		return this.titleName;
	}

	public void setTitleName(String titleName) {
		this.titleName = titleName;
	}

	/**       
	 * F01 险类档案
	 */

	@Column(name = "F01")
	public String getF01() {
		return this.f01;
	}

	public void setF01(String f01) {
		this.f01 = f01;
	}

	/**       
	 * F02保监会分�?
	 */

	@Column(name = "F02")
	public String getF02() {
		return this.f02;
	}

	public void setF02(String f02) {
		this.f02 = f02;
	}

	/**       
	 * F03核算单位
	 */

	@Column(name = "F03")
	public String getF03() {
		return this.f03;
	}

	public void setF03(String f03) {
		this.f03 = f03;
	}

	/**       
	 * F05险种档案
	 */

	@Column(name = "F05")
	public String getF05() {
		return this.f05;
	}

	public void setF05(String f05) {
		this.f05 = f05;
	}

	/**       
	 * F04部门档案
	 */

	@Column(name = "F04")
	public String getF04() {
		return this.f04;
	}

	public void setF04(String f04) {
		this.f04 = f04;
	}

	/**       
	 * F06业务性质
	 */

	@Column(name = "F06")
	public String getF06() {
		return this.f06;
	}

	public void setF06(String f06) {
		this.f06 = f06;
	}

	/**       
	 * F07业务来源
	 */

	@Column(name = "F07")
	public String getF07() {
		return this.f07;
	}

	public void setF07(String f07) {
		this.f07 = f07;
	}

	/**       
	 * F08车型档案
	 */

	@Column(name = "F08")
	public String getF08() {
		return this.f08;
	}

	public void setF08(String f08) {
		this.f08 = f08;
	}

	/**       
	 * F09共保人档�?
	 */

	@Column(name = "F09")
	public String getF09() {
		return this.f09;
	}

	public void setF09(String f09) {
		this.f09 = f09;
	}

	/**       
	 * F10再保人档�?
	 */

	@Column(name = "F10")
	public String getF10() {
		return this.f10;
	}

	public void setF10(String f10) {
		this.f10 = f10;
	}

	/**       
	 * F11客商辅助核算
	 */

	@Column(name = "F11")
	public String getF11() {
		return this.f11;
	}

	public void setF11(String f11) {
		this.f11 = f11;
	}

	/**       
	 * F13 险别档案
	 */

	@Column(name = "F13")
	public String getF13() {
		return this.f13;
	}

	public void setF13(String f13) {
		this.f13 = f13;
	}

	/**       
	 * F12业务员档�?
	 */

	@Column(name = "F12")
	public String getF12() {
		return this.f12;
	}

	public void setF12(String f12) {
		this.f12 = f12;
	}

	/**       
	 * F14 投资品种
	 */

	@Column(name = "F14")
	public String getF14() {
		return this.f14;
	}

	public void setF14(String f14) {
		this.f14 = f14;
	}

	/**       
	 * F15 农业补贴来源
	 */

	@Column(name = "F15")
	public String getF15() {
		return this.f15;
	}

	public void setF15(String f15) {
		this.f15 = f15;
	}

	/**       
	 * F16
	 */

	@Column(name = "F16")
	public String getF16() {
		return this.f16;
	}

	public void setF16(String f16) {
		this.f16 = f16;
	}

	/**       
	 * F17
	 */

	@Column(name = "F17")
	public String getF17() {
		return this.f17;
	}

	public void setF17(String f17) {
		this.f17 = f17;
	}

	/**       
	 * F18
	 */

	@Column(name = "F18")
	public String getF18() {
		return this.f18;
	}

	public void setF18(String f18) {
		this.f18 = f18;
	}

	/**       
	 * F19
	 */

	@Column(name = "F19")
	public String getF19() {
		return this.f19;
	}

	public void setF19(String f19) {
		this.f19 = f19;
	}

	/**       
	 * F20
	 */

	@Column(name = "F20")
	public String getF20() {
		return this.f20;
	}

	public void setF20(String f20) {
		this.f20 = f20;
	}

	/**       
	 * F21
	 */

	@Column(name = "F21")
	public String getF21() {
		return this.f21;
	}

	public void setF21(String f21) {
		this.f21 = f21;
	}

	/**       
	 * F22
	 */

	@Column(name = "F22")
	public String getF22() {
		return this.f22;
	}

	public void setF22(String f22) {
		this.f22 = f22;
	}

	/**       
	 * F23
	 */

	@Column(name = "F23")
	public String getF23() {
		return this.f23;
	}

	public void setF23(String f23) {
		this.f23 = f23;
	}

	/**       
	 * F24
	 */

	@Column(name = "F24")
	public String getF24() {
		return this.f24;
	}

	public void setF24(String f24) {
		this.f24 = f24;
	}

	/**       
	 * F25
	 */

	@Column(name = "F25")
	public String getF25() {
		return this.f25;
	}

	public void setF25(String f25) {
		this.f25 = f25;
	}

	/**       
	 * F26
	 */

	@Column(name = "F26")
	public String getF26() {
		return this.f26;
	}

	public void setF26(String f26) {
		this.f26 = f26;
	}

	/**       
	 * F27现金流量项目
	 */

	@Column(name = "F27")
	public String getF27() {
		return this.f27;
	}

	public void setF27(String f27) {
		this.f27 = f27;
	}

	/**       
	 * F28 �?来单�?
	 */

	@Column(name = "F28")
	public String getF28() {
		return this.f28;
	}

	public void setF28(String f28) {
		this.f28 = f28;
	}

	/**       
	 * F29银行代码
	 */

	@Column(name = "F29")
	public String getF29() {
		return this.f29;
	}

	public void setF29(String f29) {
		this.f29 = f29;
	}

	/**       
	 * F30帐户档案
	 */

	@Column(name = "F30")
	public String getF30() {
		return this.f30;
	}

	public void setF30(String f30) {
		this.f30 = f30;
	}

	/**       
	 * 创建日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDAT")
	public Date getCreateDat() {
		return this.createDat;
	}

	public void setCreateDat(Date createDat) {
		this.createDat = createDat;
	}

	/**       
	 * 创建人代�?
	 */

	@Column(name = "CREATECODE")
	public String getCreateCode() {
		return this.createCode;
	}

	public void setCreateCode(String createCode) {
		this.createCode = createCode;
	}

	/**       
	 * 有效状�??(0 无效,1 有效)
	 */

	@Column(name = "VALIDSTATUS")
	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	/**       
	 * 修改日期
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDATE")
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**       
	 * 修改人代�?
	 */

	@Column(name = "UPDATECODE")
	public String getUpdateCode() {
		return this.updateCode;
	}

	public void setUpdateCode(String updateCode) {
		this.updateCode = updateCode;
	}

	/**       
	 * 备注
	 */

	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**       
	 * 预留标志
	 */

	@Column(name = "FLAG")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}
