package cn.com.hy369.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SaaUser generated by Tools.Don't edit.
 */
@Entity
@Table(name = "learningcard")
public class LearningCard implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 学习卡代码 */
	private String cardCode;
	/** 学习卡名称 */
	private String passWord;
	/** 学习卡类型代码 */
	private String cardTypeCode;
	/** 电话号码 */
	private String phoneNo;
	/** 开始使用日期 */
	private Date startDate;
	/** 结束使用日期 */
	private Date endDate;
	/** 创建日期 */
	private Date createDate;
	public LearningCard() {
	}
	/**
	 * 学习卡号码
	 * @return
	 */
	@Id
	@Column(name = "CARDCODE")
	public String getCardCode() {
		return cardCode;
	}
	public void setCardCode(String cardCode) {
		this.cardCode = cardCode;
	}
	/**
	 * 密码
	 * @return
	 */
	@Column(name = "PASSWORD")
	public String getPassWord() {
		return passWord;
	}
	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}
	/**
	 * 学习卡类型代码
	 * @return
	 */
	@Column(name = "CARDTYPECODE")
	public String getCardTypeCode() {
		return cardTypeCode;
	}
	public void setCardTypeCode(String cardTypeCode) {
		this.cardTypeCode = cardTypeCode;
	}
	/**
	 * 电话号码
	 * @return
	 */
	@Column(name = "PHONENO")
	public String getPhoneNo() {
		return phoneNo;
	}
	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}
	/**
	 * 登陆起始日期
	 * @return
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "STARTDATE")
	public Date getStartDate() {
		return startDate;
	}
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	/**
	 * 结束日期
	 * @return
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDATE")
	public Date getEndDate() {
		return endDate;
	}
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	/**
	 * 创建日期
	 * @return
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDATE")
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
}
