package cn.com.hy369.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SaaUser generated by Tools.Don't edit.
 */
@Entity
@Table(name = "learningcardtype")
public class LearningCardType implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 学习卡类型代码 */
	private String cardTypeCode;
	/** 学习卡类型名称 */
	private String cardTypeName;
	/** 金额 */
	private BigDecimal cardDeno;
	/** 默认时间 */
	private Long defalutTime;
	private Date createDate;
	public LearningCardType() {
	}
	/**
	 * 学习卡类型代码
	 * @return
	 */
	@Id
	@Column(name = "CARDTYPECODE")
	public String getCardTypeCode() {
		return cardTypeCode;
	}
	public void setCardTypeCode(String cardTypeCode) {
		this.cardTypeCode = cardTypeCode;
	}
	/**
	 * 学习卡类型名称
	 * @return
	 */
	@Column(name = "CARDTYPENAME")
	public String getCardTypeName() {
		return cardTypeName;
	}
	public void setCardTypeName(String cardTypeName) {
		this.cardTypeName = cardTypeName;
	}
	/**
	 * 金额
	 * @return
	 */
	@Column(name = "CARDDENO")
	public BigDecimal getCardDeno() {
		return cardDeno;
	}
	public void setCardDeno(BigDecimal cardDeno) {
		this.cardDeno = cardDeno;
	}
	/**
	 * 默认天数
	 * @return
	 */
	@Column(name = "DEFALUTTIME")
	public Long getDefalutTime() {
		return defalutTime;
	}
	public void setDefalutTime(Long defalutTime) {
		this.defalutTime = defalutTime;
	}
	/**
	 * 创建日期
	 * @return
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDATE")
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
}
